services:
 app:
   build: .
   ports:
     - "5500:5500"
   environment:
     - PORT=5500
     - MONGODB_URI=mongodb://db:27017/registerApp
   depends_on:
     - db
 db:
   image: mongo:5.0
   volumes:
     - mongo-data:/data/db

volumes:
 mongo-data: